<%@page import="org.siemac.metamac.core.common.util.swagger.SwaggerUtils"%>
<%@page pageEncoding="UTF-8"%>
<%@ page import="org.siemac.metamac.core.common.util.InternationalizationUtils" %>
<%@ page import="org.siemac.metamac.core.common.util.MessagesResourceBundle"%>
<%
   String locale = InternationalizationUtils.getInstance().getCurrentLocale(request);
   MessagesResourceBundle messagesResource = new MessagesResourceBundle(locale, "i18n.messages");
   pageContext.setAttribute("msg", messagesResource);
%>
{
   "swagger":"2.0",
   "info":{
      "description":"${msg['api.doc.swagger.info.description']}",
      "version":"2.0.1-SNAPSHOT",
      "title":"${msg['api.doc.swagger.title']}"
   },
   "host":"<%=SwaggerUtils.getApiBaseURLForSwagger()%>",
   "schemes":[

   ],
   "tags" : [
    {
      "name" : "${msg['api.doc.swagger.tag.structure']}",
      "description" : "${msg['api.doc.swagger.tags.1.description']}"
    },
    {
      "name" : "${msg['api.doc.swagger.tag.data']}",
      "description" : "${msg['api.doc.swagger.tags.0.description']}"
    }
  ],
   "definitions": <jsp:include page="definitions.jsp" /> ,
   "paths":{
      "/v2.1/datastructure":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.datastructure.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findDataStructure_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/datastructure/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.datastructure.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findDataStructure_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/datastructure/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.datastructure.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findDataStructure_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/datastructure/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.datastructure.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findDataStructure_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categoryscheme":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categoryscheme.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findCategoryScheme_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categoryscheme/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categoryscheme.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findCategoryScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categoryscheme/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categoryscheme.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findCategoryScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categoryscheme/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categoryscheme.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findCategoryScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/conceptscheme":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.conceptscheme.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findConceptScheme_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/conceptscheme/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.conceptscheme.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findConceptScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/conceptscheme/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.conceptscheme.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findConceptScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/conceptscheme/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.conceptscheme.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findConceptScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/codelist":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.codelist.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findCodelist_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/codelist/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.codelist.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findCodelist_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/codelist/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.codelist.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findCodelist_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/codelist/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.codelist.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findCodelist_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationscheme":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationscheme.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findOrganisationScheme_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationscheme/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationscheme.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findOrganisationScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationscheme/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationscheme.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findOrganisationScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationscheme/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationscheme.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findOrganisationScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/agencyscheme":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.agencyscheme.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findAgencyScheme_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/agencyscheme/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.agencyscheme.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findAgencyScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/agencyscheme/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.agencyscheme.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findAgencyScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/agencyscheme/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.agencyscheme.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findAgencyScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataproviderscheme":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataproviderscheme.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findDataProviderScheme_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataproviderscheme/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataproviderscheme.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findDataProviderScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataproviderscheme/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataproviderscheme.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findDataProviderScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataproviderscheme/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataproviderscheme.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findDataProviderScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataconsumerscheme":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataconsumerscheme.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findDataConsumerScheme_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataconsumerscheme/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataconsumerscheme.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findDataConsumerScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataconsumerscheme/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataconsumerscheme.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findDataConsumerScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataconsumerscheme/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataconsumerscheme.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findDataConsumerScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationunitscheme":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationunitscheme.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findOrganisationUnitScheme_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationunitscheme/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationunitscheme.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findOrganisationUnitScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationunitscheme/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationunitscheme.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findOrganisationUnitScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/organisationunitscheme/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.organisationunitscheme.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findOrganisationUnitScheme_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataflow":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataflow.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findDataFlow_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataflow/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataflow.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findDataFlow_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataflow/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataflow.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findDataFlow_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/dataflow/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.dataflow.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findDataFlow_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categorisation":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categorisation.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findCategorisation_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categorisation/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categorisation.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findCategorisation_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categorisation/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categorisation.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findCategorisation_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/categorisation/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}", "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.categorisation.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findCategorisation_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/contentconstraint":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.contentconstraint.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findContentConstraint_GET",
            "produces":[
               "application/xml"
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/contentconstraint/{agencyID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.contentconstraint.agencyID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_findContentConstraint_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/contentconstraint/{agencyID}/{resourceID}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.contentconstraint.agencyID.resourceID.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_findContentConstraint_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/contentconstraint/{agencyID}/{resourceID}/{version}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.structure']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.contentconstraint.agencyID.resourceID.version.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_agencyID_resourceID_version_findContentConstraint_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"agencyID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.agencyID.description']}",
                  "required":true
               },
               {
                  "name":"resourceID",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.resourceID.description']}",
                  "required":true
               },
               {
                  "name":"version",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.version.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/data/{flowRef}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.data.flowRef.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_findData_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"flowRef",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.flowRef.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/data/{flowRef}/{key}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.data.flowRef.key.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_key_findData_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"flowRef",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.flowRef.description']}",
                  "required":true
               },
               {
                  "name":"key",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.key.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      },
      "/v2.1/data/{flowRef}/{key}/{providerRef}":{
         "get":{
            "tags" : [ "${msg['api.doc.swagger.tag.data']}" ],
            "description":"${msg['api.doc.swagger.paths.v2_1.data.flowRef.key.providerRef.get.description']}",
            "operationId":"resource_SDMXRegistryV2_1_key_providerRef_findData_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"flowRef",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.flowRef.description']}",
                  "required":true
               },
               {
                  "name":"key",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.key.description']}",
                  "required":true
               },
               {
                  "name":"providerRef",
                  "in":"path",
                  "type":"string",
                  "description":"${msg['api.doc.swagger.paths.parameters.providerRef.description']}",
                  "required":true
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "$ref":"#/definitions/xml_ns3_StructureType"
                  },
                  "headers":{

                  },
                  "description":"${msg['api.doc.swagger.paths.responses.200']}"
               },
               "404":{
                  "description":"${msg['api.doc.swagger.paths.responses.404']}"
               },
               "406":{
                  "description":"${msg['api.doc.swagger.paths.responses.406']}"
               },
               "500":{
                  "description":"${msg['api.doc.swagger.paths.responses.500']}"
               },
               "503":{
                  "description":"${msg['api.doc.swagger.paths.responses.503']}"
               }
            }
         }
      }
   }
}