###
# Dockerfile usado para consutruir la imagen del sdmx-registry
#
# Antes de construir la imagen debemos haber compilado previamente el proyecto (desde el directorio raíz):
#
# mvn clean package
#
# A continuación podremos construir la imagen ejecutando siempre desde el directorio raíz del proyecto:
#
# docker build -f dockerfiles/Dockerfile -t sdmx-registry:<version> .
#
# Para ejecutar un contenedor asociado a esta imagen:
# docker run -i --rm -p 8080:8080 sdmx-registry:<version>
#
# Para ejecutar con opciones de debug habilitadas:
# docker run -i --rm \
# -e JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n" \
# -p 8080:8080 \
# -p 5005:5005 \
# sdmx-registry:<version>
###

FROM tomcat:9.0.98-jdk8
LABEL MAINTAINER=info@arte-consultores.com

RUN mkdir -p /data/edatos/sdmx-registry/conf

COPY dockerfiles/conf /data/edatos/sdmx-registry/conf
COPY metamac-registry-web/target/*.war /usr/local/tomcat/webapps/sdmx-registry.war

ENV LANG='es_ES.UTF-8'
ENV SDMX_REGISTRYCONF_PATH='file:/data/edatos/sdmx-registry/conf/environment.xml'
ENV STATISTICAL_RESOURCES_CONF_PATH='file:/data/edatos/sdmx-registry/conf/environment.xml'

RUN env

CMD ["catalina.sh", "run"]